name: bikaji
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.6+23

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.1.1
  percent_indicator: ^4.0.0
  http: ^0.13.5
  image_picker: ^0.8.4
  cached_network_image: ^3.2.0
  smooth_star_rating_null_safety: ^1.0.4+2
  animator:
  sqflite:
  path_provider:
  shimmer: ^1.1.2
  #geolocator: '^5.1.1'
  #geocoder: ^0.2.1
  flutter_inappwebview: ^5.4.4+3
  package_info: ^0.4.3+2
  #app_settings: ^4.0.0
  shared_preferences: ^2.0.15
  #clipboard_manager: ^0.0.4
  share: ^2.0.4
  dotted_border: ^2.0.0+2
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^12.0.1+1
  #firebase_messaging: ^6.0.13
  #firebase_crashlytics: ^0.1.3+3
  autocomplete_textfield: ^2.0.1
  firebase_analytics: ^10.3.0
  url_launcher: ^6.1.6
  syncfusion_flutter_pdfviewer: ^20.2.43-beta
  photo_view: ^0.14.0
  #webview_flutter: ^3.0.4
  intl: ^0.17.0
  uni_links: ^0.4.0
  #paytm: ^1.0.0
  flutter_bloc: ^7.3.3
  equatable: ^2.0.5
  #flutter_image_compress: ^1.0.0
  store_redirect: ^2.0.1
  #facebook_analytics: ^0.1.4
  flutter_widget_from_html_core: ^0.8.5+3

  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bikaji_logo.png
    - assets/bikaneri_bhujia.png
    - assets/dummy_pic.png
    - assets/login_bg.jpg
    - assets/coins.png
    - assets/bikaji_logo_small.png
    - assets/heart.png
    - assets/empty_bag.png
    - assets/user_pic.png
    - assets/no_image.png
    - assets/banner_2.jpg
    - assets/corporate_order.jpg
    - assets/corporate_order_new.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-RegularItalic.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
