/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData cart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData favorite_border = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData coins = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData credit_card_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_about = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_bulk_order = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_cart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData ic_cart_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ic_categories = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ic_city = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData ic_confirm = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData ic_coupon = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ic_detect = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ic_dob = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData ic_faqs = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ic_fav = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData ic_filter = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData ic_gift_wrap = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData ic_heart = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData ic_help_line = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData ic_landmark = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData ic_mail = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData ic_more = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData ic_my_addresses = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData ic_notification = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData ic_offers = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData ic_past_orders = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData ic_payment = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData ic_profile = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData ic_search = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData ic_share = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData ic_shipping = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData ic_sort = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData ic_terms = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData ic_wallet = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData bikaji_logo = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData checkmark_cicle = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
}
